name: CPython GMIC MacOS Optimized Build & Release on Tag
# Imitating https://github.com/vinecopulib/pyvinecopulib/blob/master/.github/workflows/pypi.yml

# Allow running this job only for v* tag pushes
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-macos-optimized-test-ontag-release:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Detect G'MIC target version
        run: echo "GMIC_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build and test gmic-py ${{ env.GMIC_VERSION }} on MacOS
        working-directory: ./
        env:
          TWINE_PASSWORD_GITHUB_SECRET: ${{ secrets.TWINE_PASSWORD_GITHUB_SECRET }} # For build_tools.bash 11_send_to_pypi
          PYTHON3: python3
          PIP3: pip3
          CIBW_BUILD: cp3*-*macosx*
          CIBW_SKIP: cp35* # Do not support Python 3.5 anymore
          CIBW_ENVIRONMENT: "CC='/usr/local/opt/llvm@6/bin/clang' CXX='/usr/local/opt/llvm@6/bin/clang++' COMPILER_INDEX_STORE_ENABLE='NO'"
          CIBW_BEFORE_BUILD: pip install -r dev-requirements.txt
          CIBW_TEST_REQUIRES: pytest numpy Pillow
          CIBW_TEST_COMMAND: python -W default -m pytest {project}/tests/test_gmic_py.py {project}/tests/test_gmic_numpy.py -vvv -rxXs
          CIBW_BUILD_VERBOSITY: 3
          MACOSX_DEPLOYMENT_TARGET: 10.10
        run: |
          # llvm 9 (latest) might cause issue with c++20 pre-support, see https://trac.macports.org/ticket/59575 and https://github.com/dtschump/gmic-py/commit/618d9d317d55aa7af3f85e92bfd07f06efea491f/checks?check_suite_id=368364476
          # using llvm v6 instead
          brew install pkg-config fftw libpng libomp llvm@6 coreutils
          MACOSX_DEPLOYMENT_TARGET=10.10 pip install git+https://github.com/mayeut/cibuildwheel.git
          MACOSX_DEPLOYMENT_TARGET=10.10 python -m cibuildwheel --output-dir wheelhouse && bash build_tools.bash 11_send_to_pypi
          echo "Mac OS wheelhouse after cibuildwheel and sending to pypi.org looks like:"
          echo `greadlink -f wheelhouse`
          ls -l wheelhouse
      - name: upload wheelhouse as artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-gmicpy-optimized-released-wheels
          path: wheelhouse/
